Use correct constants
hayden4r4/blackscholes-rust pull request #45
Opened 2024-08-20 19:24 UTC by claireratigan

I got an error because of a `t` value between `0.21` and `SMALL_T_EXPANSION_OF_NORMALISED_BLACK_THRESHOLD`, which resulted in `normalised_black_call` dispatching to `small_t_expansion_of_normalised_black_call` and then failing the expect.

This fixes that.

2024-08-27 14:26 UTC, day01 commented on src/lets_be_rational/black.rs
> +    if t >= SMALL_T_EXPANSION_OF_NORMALISED_BLACK_THRESHOLD {
can you add some tests ?

2024-08-27 14:29 UTC, day01 commented on src/lets_be_rational/black.rs
> -    let tau_small: f64 = 2.0 * f64::EPSILON.sqrt().powi(16);
like

2024-08-27 14:30 UTC, day01 commented on src/lets_be_rational/black.rs
>  /// * `Some(f64)` containing the computed value if t < 0.21
so we need explanation and info in summary

2024-08-27 18:26 UTC, day01 requested changes
Tests and summary fixes

2024-09-12 20:00 UTC, claireratigan commented
@day01 let me know if this addresses your comments

2024-09-13 14:57 UTC, day01 commented on tests/test_pricing.rs
> +    .calc_rational_price()
almost, please add an assert to compare results.

2024-09-13 14:59 UTC, day01 commented
It almost ok, please modify a little test to verify correctness of calculation via assert will be great.
much appreciate

2024-09-15 10:19 UTC, day01 approved these changes

2024-09-15 10:19 UTC, day01 commented
Great work, thank you :)

2024-09-15 10:20 UTC, merged